# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3e3230c6e55e91bb4ae06bbdf4bc53871e3a39a1b2f77efa5b534e1e0ae91491526bd9513626d72d791a8071094e6daa2599fd3b5c8f1406f36ce941650877

test:
  secret_key_base: 35646a9e761593d57da08c8d5b29db81dcb7e25b1d23f388519ee170c123cae4d7e394569d67fd9c83e47f11e273e1c010b87dc87161039aed07fa534111850f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
